site_name: My Docs
nav:
    - home: index.md
    - network:
        - 'Interface Errors': network/errors.md
        - 'Switching': network/switching.md
        - 'DHCP snooping': network/dhcpsnooping.md
        - 'NLB': network/switching.md
        - 'Switch cisco': network/cisco_sw.md
        - 'Switch juniper ex': network/juniper_ex.md
        - 'Switch huawei s57': network/huawei.md
        - 'Switch eltex': network/eltex.md
        - 'Switch tfortis': network/tfortis.md
        - 'Router Cisco': network/cisco_r.md
    - work:
        - 'Miniconda': work/miniconda.md
        - 'Mkdocs': work/mkdocs.md
theme:
  name: material
