site_name: My Docs
nav:
    - 'About': index.md
    - monitoring:
        - 'PromQL, MetricQL': monitoring/promql_metricql.md
        - 'Vmagent, snmp_exporter': monitoring/snmp_exporter.md
        - 'Telegraf vs vmagent': monitoring/telegraf_vmagent.md
        - 'Telegraf snmp': monitoring/telegraf_snmp.md
        - 'netflow, sflow': monitoring/sflow.md
    - network:
        - 'Interface Errors': network/errors.md
        - 'Switching': network/switching.md
        - 'DHCP snooping': network/dhcpsnooping.md
        - 'NLB': network/nlb.md
        - 'TCP MSS': network/tcp_mss.md
        - 'Flowcontrol': network/flowcontrol.md
        - 'PoE': network/poe.md
        - 'СКС': network/sks.md
        - 'Switch list for vxlan': network/vxlan_sw.md
        - 'Switch cisco': network/cisco_sw.md
        - 'Switch juniper ex': network/juniper_ex.md
        - 'Switch huawei s57': network/huawei.md
        - 'Switch eltex': network/eltex.md
        - 'Switch tfortis': network/tfortis.md
        - 'Router cisco': network/cisco_r.md
        - 'Router vyos': network/vyos.md
    - voip:
        - 'Softphones': voip/softphone.md
        - 'Cisco E1 gateway': voip/cisco_e1_gateway.md
        - 'Cisco CDR for gateway': voip/cisco_gw_cdr.md
        - 'Cisco CME(CUCME)': voip/cisco_cme.md
        - 'Cisco COR list': voip/cisco_cor.md
        - 'Cisco CUBE': voip/cisco_cube.md
        - 'Cisco voip notes': voip/cisco_voip.md
    - work:
        - 'AdGuardHome': work/adguardhome.md
        - 'Ansible for ntwrk': work/ansible_ntwrk.md
        - 'Miniconda': work/miniconda.md
        - 'Mkdocs': work/mkdocs.md
        - 'Proxy for app': work/app_proxy.md
        - 'Empty, sshpass': work/empty.md
        - 'Tacacs': work/tacacs.md
        - 'Translit, recode': work/translit.md
        - 'Speed test': work/speedtest.md
theme:
  name: material
