site_name: My Docs
nav:
    - 'About': index.md
    - monitoring:
        - 'Telegraf vs vmagent': monitoring/telegraf_vmagent.md
        - 'Telegraf snmp': monitoring/telegraf_snmp.md
    - network:
        - 'Interface Errors': network/errors.md
        - 'Switching': network/switching.md
        - 'DHCP snooping': network/dhcpsnooping.md
        - 'NLB': network/nlb.md
        - 'TCP MSS': network/tcp_mss.md
        - 'flowcontrol': network/flowcontrol.md
        - 'Switch list for vxlan': network/vxlan_sw.md
        - 'Switch cisco': network/cisco_sw.md
        - 'Switch juniper ex': network/juniper_ex.md
        - 'Switch huawei s57': network/huawei.md
        - 'Switch eltex': network/eltex.md
        - 'Switch tfortis': network/tfortis.md
        - 'Router cisco': network/cisco_r.md
    - voip:
        - 'Softphones': voip/softphone.md
        - 'Voip cisco': voip/cisco_voip.md
    - work:
        - 'AdGuardHome': work/adguardhome.md
        - 'Miniconda': work/miniconda.md
        - 'Mkdocs': work/mkdocs.md
        - 'Proxy for app': work/app_proxy.md
theme:
  name: material
